// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njavbigewfwjjgbpuufd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qYXZiaWdld2Z3ampnYnB1dWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2Mzk0MzQsImV4cCI6MjA1NzIxNTQzNH0.mdx-73EW0z5GsoKGBPV_H7F28UPyEHZ9R3xvIhYuHLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);