// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtnwwpiriefxkuhdpyhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0bnd3cGlyaWVmeGt1aGRweWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MzE2NjEsImV4cCI6MjA1NjIwNzY2MX0.TdXEMoJWHVTc9raPyuqduV_42qg6hkMYqXxvUl8OKjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);